---
name: Docker Release

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup faas-cli
        run: |
          curl -sSL https://cli.openfaas.com | sh
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_AUTH_TOKEN }}
      - name: Pull template
        run: |
          git clone https://github.com/tschaefer/openfaas-perl-mojo-template -b full-mojo _template
          mv _template/template .
          rm -rf _template
      - name: Build and Push
        run: |
          faas-cli publish \
            --platforms linux/amd64,linux/arm64 \
            --build-label org.opencontainers.image.source=https://github.com/tschaefer/openfaas-minio-notify-function \
            --build-label org.opencontainers.image.licenses=MIT \
            --build-label org.opencontainers.image.description="OpenFaaS Minio bucket event notification"
